server:
  port: 9001
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.12.69:3306/big_event?serverTimezone=UTC
    username: root
    password: Twx18874158!
  data:
    redis:
      host: 8.130.12.69
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath: mapper/*.xml
#  开启驼峰命名和下划线命名自动转换
debug: true

logging:
  level:
    com.example.bigme.mapper: trace