spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.236.140:3306/big_event
    username: root
    password: root
  data:
    redis:
      host: 192.168.236.140
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  开启驼峰命名和下划线命名自动转换
debug: true
logging:
  level:
    com.example.bigme.mapper: trace